### ISSUE TITLE
Does methyICC works for non-whole-blood tissues?

### ISSUE THREAD

**Issue by Niinleslie** [stephaniehicks/methylCC#4]
Hi,
Can I apply methyICC to esitmate immune cell fractions of WGBS data from liver tumor tissues?
If so, how should I prepare the input and ref data? 
Thanks!

**Comment by GMFranceschini** [comment]
I have a similar issue so I post here and add a comment: in principle, I think you can modify the package to use `find_dmrs()` on something different from `flow.Sorted.Blood450k`. I am currently trying to achieve that since I don't think this will violate any key assumption of the work. In your case, you would need to add at least the hepatocyte profiles, since you expect your biopsies to contain liver cells + other stuff. The TCGA data should be suitable to call those DMRs, but adapting the code is not straight forward and only the authors can tell us if that is correct. In any case, I think that more plasticity at the level of DMR selection would really broaden the application of this package.

**Comment by stephaniehicks** [comment]
Thanks @Niinleslie @GMFranceschini for opening the issue. Add another request to this thread too (https://support.bioconductor.org/p/132689/#132691). 

There seems to be a sufficient enough interest in making this flexible for other types of cell types besides whole blood. This summer I do not have time to make those changes to the software, but I'm happy to work these ideas this fall. 

Thanks for your interest in the package and I appreciate your patience. I will leave the issue open for now as a reminder to get back to this asap.

**Comment by stephaniehicks** [comment]
Hi everyone, just looping back here to say that I am not actively working in this area anymore. I plan to close the issue.
